#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d DP-2 DVI-D-0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Custom rules

# Keyboard Layout
setxkbmap -layout fr

# Monitor order
xrandr --output DP-2 --left-of DVI-D-0

# Background
nitrogen --set-scaled ~/grass.jpg

# Polybar
../polybar/launch.sh
